adding showterm screencast support
* updated install and configure script
* network proxy code refactoring
* prompt file rename to generic
* emacs switcher update

diff --git a/shell/shellrc.d/network b/shell/shellrc.d/network
--- a/shell/shellrc.d/network
+++ b/shell/shellrc.d/network
@@ -2,35 +2,35 @@ alias dcadmin='telnet localhost 53696'
 
 function proxy_on() {
     export no_proxy="localhost,127.0.0.1,localaddress,.localdomain.com"
+	address=($@)
 
-    if (( $# > 0 )); then
-        valid=$(echo $@ | sed -n 's/\([0-9]\{1,3\}.\)\{4\}:\([0-9]\+\)/&/p')
-        if [[ $valid != $@ ]]; then
-            >&2 echo "Invalid address"
-            return 1
-        fi
+    if (( $# == 0 )); then
+		echo -n "username: "; read username
+		if [[ $username != "" ]]; then
+			echo -n "password: "
+			read -es password
+			local auth="$username:$password@"
+		fi
 
-        export http_proxy="http://$1/"
-        export https_proxy=$http_proxy
-        export ftp_proxy=$http_proxy
-        export rsync_proxy=$http_proxy
-        echo "Proxy environment variable set."
-        return 0
+		echo -n "server: "; read server
+		echo -n "port: "; read port
+		local address="$server:$port"
+	fi
+
+    valid=$(echo $address | sed -n 's/^\([0-9]\{1,3\}.\)\{4\}:\([0-9]\+ *\)\?$/&/p')
+    if [[ $valid != $address ]]; then
+        >&2 echo 'Invalid address!'
+		>&2 echo 'For authentification use without agruments.'
+		echo $address
+		echo $auth
+        return 1
     fi
 
-    echo -n "username: "; read username
-    if [[ $username != "" ]]; then
-        echo -n "password: "
-        read -es password
-        local pre="$username:$password@"
-    fi
-
-    echo -n "server: "; read server
-    echo -n "port: "; read port
-    export http_proxy="http://$pre$server:$port/"
+    export http_proxy="http://$auth$address/"
     export https_proxy=$http_proxy
     export ftp_proxy=$http_proxy
     export rsync_proxy=$http_proxy
+    echo "Proxy environment variable set."
 }
 
 function proxy_off(){
@@ -40,3 +40,6 @@ function proxy_off(){
     unset rsync_proxy
     echo -e "Proxy environment variable removed."
 }
+
+# proxy using socat
+# exec socat STDIO PROXY:$_proxy:$1:$2,proxyport=$_proxyport
